spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: root
    dbcp2:
      test-while-idle: true
      validation-query: SELECT 1
    driverClassName: com.mysql.jdbc.Driver

  jpa:
    generate-ddl: true
    database-platform=org:
      hibernate:
        dialect:
          MySQL5InnoDBDialect:
    hibernate:
      ddl-auto: update